"""rename_professors_to_teachers

Revision ID: 902ed7e6bca5
Revises: 40c69a6afaab
Create Date: 2025-12-11 08:10:39.137121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '902ed7e6bca5'
down_revision: Union[str, None] = '40c69a6afaab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create teachers table
    op.create_table('teachers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('specialty', sa.String(length=255), nullable=True),
    sa.Column('hire_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_teachers_id'), 'teachers', ['id'], unique=False)
    
    # Copy data from professors to teachers
    op.execute("""
        INSERT INTO teachers (id, user_id, cpf, phone, specialty, hire_date, created_at, updated_at)
        SELECT id, user_id, cpf, phone, specialty, hire_date, created_at, updated_at
        FROM professors
    """)
    
    # Update sequence to continue from last professor id
    op.execute("SELECT setval('teachers_id_seq', (SELECT MAX(id) FROM teachers))")
    
    # Add teacher_id column to classes
    op.add_column('classes', sa.Column('teacher_id', sa.Integer(), nullable=True))
    
    # Copy professor_id to teacher_id
    op.execute("UPDATE classes SET teacher_id = professor_id")
    
    # Drop old foreign key and add new one
    op.drop_constraint('classes_professor_id_fkey', 'classes', type_='foreignkey')
    op.create_foreign_key(None, 'classes', 'teachers', ['teacher_id'], ['id'])
    
    # Drop old column and table
    op.drop_column('classes', 'professor_id')
    op.drop_index('ix_professors_id', table_name='professors')
    op.drop_table('professors')
    
    # Update UserRole enum to include TEACHER instead of PROFESSOR
    op.execute("ALTER TYPE userrole RENAME VALUE 'PROFESSOR' TO 'TEACHER'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classes', sa.Column('professor_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'classes', type_='foreignkey')
    op.create_foreign_key('classes_professor_id_fkey', 'classes', 'professors', ['professor_id'], ['id'])
    op.drop_column('classes', 'teacher_id')
    op.create_table('professors',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cpf', sa.VARCHAR(length=11), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('specialty', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('hire_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='professors_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='professors_pkey'),
    sa.UniqueConstraint('cpf', name='professors_cpf_key'),
    sa.UniqueConstraint('user_id', name='professors_user_id_key')
    )
    op.create_index('ix_professors_id', 'professors', ['id'], unique=False)
    op.drop_index(op.f('ix_teachers_id'), table_name='teachers')
    op.drop_table('teachers')
    # ### end Alembic commands ###
